services:
  api:
    container_name: ephemeral-api
    build:
      context: .
    environment:
      ENV: ${ENV:-development}
      MONGO_URI: ${MONGO_URI:-mongodb://mongo:27017}
      DB_NAME: ${DB_NAME:-ephemeral}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_USER: ${REDIS_USER:-}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      PORT: ${PORT:-8000}
    ports:
      - "${PORT:-8000}:8000"
